apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: {{ .Values.storage.name | default "storage-minio" | quote }}
  {{- include "wp.annotations.block" (dict "global" .Values.globalAnnotations "local" .Values.storage.annotations) | nindent 2 }}
spec:
  package: {{ required "values.storage.package is required" .Values.storage.package | quote }}
  skipDependencyResolution: true
