apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: {{ .Values.environmentconfig.name | default "datalab" | quote }}
  {{- include "wp.annotations.block" (dict "global" .Values.globalAnnotations "local" .Values.environmentconfig.annotations) | nindent 2 }}
data:
  iam:
    realm: {{ .Values.environmentconfig.iam.realm | default "" | quote }}

  ingress:
    class: {{ .Values.environmentconfig.ingress.class | default "" | quote }}
    domain: {{ .Values.environmentconfig.ingress.domain | default "" | quote }}
    secret: {{ .Values.environmentconfig.ingress.secret | default "" | quote }}

  storage:
    endpoint: {{ .Values.environmentconfig.storage.endpoint | default "" | quote }}
    force_path_style: {{ toString (default true .Values.environmentconfig.storage.forcePathStyle) | quote }}
    provider: {{ .Values.environmentconfig.storage.provider | default "" | quote }}
    region: {{ .Values.environmentconfig.storage.region | default "" | quote }}
    secretNamespace: {{ .Values.environmentconfig.storage.secretNamespace | default "" | quote }}
    type: {{ .Values.environmentconfig.storage.type | default "" | quote }}

  network:
    serviceCIDR: {{ .Values.environmentconfig.network.serviceCIDR | default "" | quote }}

  {{- with .Values.environmentconfig.packages }}
  packages:
{{ toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.environmentconfig.auth }}
  auth:
    {{- range $k, $v := . }}
      {{- if or (kindIs "bool" $v) (ne (toString $v) "") }}
    {{ $k }}: {{ toString $v | quote }}
      {{- end }}
    {{- end }}
  {{- end }}

  {{- with .Values.environmentconfig.defaults }}
  defaults:
    {{- $q := .quota | default dict }}
    {{- if $q }}
    quota:
      {{- range $k, $v := $q }}
        {{- if or (kindIs "bool" $v) (ne (toString $v) "") }}
      {{ $k }}: {{ toString $v | quote }}
        {{- end }}
      {{- end }}
    {{- end }}

    {{- $s := .security | default dict }}
    {{- if $s }}
    security:
      {{- range $k, $v := $s }}
        {{- if or (kindIs "bool" $v) (ne (toString $v) "") }}
      {{ $k }}: {{ toString $v | quote }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
