apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-minio
spec:
  package: ghcr.io/vshn/provider-minio/provider:v0.3.0
---
apiVersion: minio.crossplane.io/v1
kind: ProviderConfig
metadata:
  name: provider-minio
spec:
  credentials:
    apiSecretRef:
      name: minio-secret
      namespace: workspace
    source: InjectedIdentity
  minioURL: https://minio.develop.eoepca.org