apiVersion: minio.crossplane.io/v1
kind: ProviderConfig
metadata:
  name: provider-minio
spec:
  credentials:
    apiSecretRef:
      name: minio-secret
      namespace: workspace
    source: InjectedIdentity
  minioURL: https://minio.develop.eoepca.org