apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ws-keycloak
rules:
  - apiGroups:
    - "epca.eo"
    resources:
    - "workspaces"
    verbs:
    - "patch"
    - "get" 
  - apiGroups:
    - "group.keycloak.crossplane.io"
    resources:
    - "memberships"
    verbs:
    - "patch"
    - "get" 
  - apiGroups:
    - "group.keycloak.crossplane.io"
    resources:
    - "groups"
    verbs:
    - "list" 