site_name: EOEPCA Workspace Building Block
site_url: https://eoepca.readthedocs.io/projects/workspace/
repo_url: https://github.com/EOEPCA/workspace/
edit_uri: "edit/main/docs/"

nav:
  - EOEPCA Documentation: https://eoepca.readthedocs.io/
  - Workspace:
    - index.md
    - Getting Started:
      - getting-started/quickstart.md
      - getting-started/concepts.md
      - getting-started/operator-view.ipynb
      - getting-started/user-view.ipynb
    - Design:
      - design/architecture.md
      - design/iam-integration.md
      - design/operational-controls.md
    - API References:
      - Workspace API ↗: https://workspace-api.develop.eoepca.org/docs
      - Storage CRD ↗: https://provider-storage.versioneer.at/latest/reference-guides/api/
      - Datalab CRD ↗: https://provider-datalab.versioneer.at/latest/reference-guides/api/

theme:
  name: material
  logo: img/favicon.ico
  favicon: img/favicon.ico
  features:
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.action.edit
    - search.highlight
    - search.share
    - search.suggest

extra_css:
  - css/eoepca.css

plugins:
  - search
  - autorefs
  - mkdocs-jupyter:
      execute: false

markdown_extensions:
  - tables
  - toc:
      permalink: ⚓︎
      toc_depth: 4
  - smarty
  - sane_lists
  - admonition
  - abbr
  - attr_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
