apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: workspaces.epca.eo
spec:
  group: epca.eo
  names:
    kind: Workspace
    plural: workspaces
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          description: >
            Workspace is a namespaced composite representing a collaborative working area.
            A primary object storage bucket with the same name as the workspace is created
            automatically. Additional buckets can be requested via `spec.extraBuckets`.
            Access to buckets owned by other workspaces can be requested via `spec.linkedBuckets`,
            and this workspace can grant access to others using `spec.grants`.
          required:
            - spec
          properties:
            spec:
              type: object
              description: Desired state of the workspace.
              required:
                - owner
              properties:
                owner:
                  type: string
                  description: >
                    Primary user for the workspace, used for default
                    ownership and access control.
                members:
                  type: array
                  description: >
                    Additional users that belong to this workspace.
                  items:
                    type: string
                  default: []
                vcluster:
                  type: string
                  description: >
                    Controls whether a virtual cluster is used for runtime:
                    - "always": always use vcluster for runtime of this workspace
                    - "never": never use vcluster for runtime of this workspace; always rely on
                      a namespace in the host cluster
                    - "auto": runtime will be managed separately (policy/quotas decide)
                  enum: [always, never, auto]
                  default: auto
                extraBuckets:
                  type: array
                  description: >
                    Additional buckets to create alongside the automatically created
                    primary bucket (which shares the workspace name). Each entry is a bucket name.
                  items:
                    type: string
                  default: []
                linkedBuckets:
                  type: array
                  description: >
                    Buckets owned by other workspaces that this workspace wants to link to.
                    Each entry is a bucket name.
                  items:
                    type: string
                  default: []
                grants:
                  type: array
                  description: >
                    Outbound access grants from this workspace’s buckets to other principals.
                    Each entry is flat and specifies the local bucket, the grantee, and the permission.
                  items:
                    type: object
                    required: [bucketName, grantee, permission]
                    properties:
                      bucketName:
                        type: string
                        description: Name of the bucket (owned by this workspace) to grant access to.
                      grantee:
                        type: string
                        description: Identifier of the principal receiving access.
                      permission:
                        type: string
                        description: Granted permission level.
                        enum: [ReadWrite, ReadOnly, WriteOnly, None]
                  default: []
            status:
              type: object
              description: Observed state of the workspace (populated by controllers).
              properties: {}
