apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: storage-minio
  annotations: {}   # filled dynamically from values.yaml
spec:
  package: ghcr.io/versioneer-tech/provider-storage/minio:0.1.0
  skipDependencyResolution: true
