globalAnnotations: {}

storage:
  name: storage-minio
  package: ghcr.io/versioneer-tech/provider-storage/minio:0.2.2
  annotations: {}

datalab:
  name: datalab-educates
  package: ghcr.io/versioneer-tech/provider-datalab/educates:0.9.2
  annotations: {}

environmentconfig:
  name: datalab
  annotations: {}
  iam:
    realm: ""
    extraAudiences: []
  ingress:
    class: ""
    domain: ""
    secret: ""
  storage:
    endpoint: ""
    forcePathStyle: true
    provider: ""
    region: ""
    secretNamespace: ""
    type: s3
    lifecycle:
      schedule: ""
  storageClasses:
    allowed: []
  network:
    externalEgressCIDRs: []
    serviceCIDR: ""
    podCIDRs: []
    blacklistIPs: []
    excludePolicies: []
  packages: []
  auth:
    type: ""
  defaults:
    quota:
      memory: ""
      storage: ""
      budget: ""
    security:
      policy: ""
      kubernetesAccess: ""
      kubernetesRole: ""
      externalEgress: ""
      internalEgress: ""
  database: 
    gateway:
      parentName: ""
      parentNamespace: ""
      sectionName: ""
    storageClassName: ""
    backupStorageClassName: ""
  mongodb:
    storageClassName: ""
  redis:
    storageClassName: ""
  qdrant:
    storageClassName: ""
