apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xworkspaces.epca.eo
spec:
  group: epca.eo
  names:
    kind: XWorkspace
    plural: xworkspaces
  claimNames:
    kind: Workspace
    plural: workspaces
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                subscription:
                  type: string
                  enum:
                    - gold
                    - silver
                    - bronze
                    - trial
                  default: trial
                owner:
                  type: string
                members:
                  type: array
                  items:
                    type: string
                  default: []
                vcluster:
                  type: string
                  enum:
                    - active
                    - suspended
                    - disabled
                  default: disabled
                extraBuckets:
                  type: array
                  items:
                    type: string
                  default: []
                grants:
                  type: array
                  items:
                    type: object
                    properties:
                      bucket:
                        type: string
                      grantees:
                        type: array
                        items:
                          type: string
                    required:
                      - bucket
                      - grantees
                  default: []
            status:
              type: object
              properties:
              required:
                - owner