apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-helm
spec:
  credentials:
    source: InjectedIdentity
---
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-terraform
spec:
  configuration: |
      terraform {
        backend "kubernetes" {
          secret_suffix     = "provider-terraform"
          namespace         = "workspace"
          in_cluster_config = true
        }
      }