apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ws-keycloak
rules:
  - apiGroups:
    - "epca.eo"
    resources:
    - "workspaces"
    verbs:
    - "patch"
    - "get" 
  - apiGroups:
    - "group.keycloak.crossplane.io"
    resources:
    - "memberships"
    verbs:
    - "patch"
    - "get" 
  - apiGroups:
    - "group.keycloak.crossplane.io"
    resources:
    - "groups"
    verbs:
    - "list" 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: provider-helm-cluster-admin
subjects:
  - kind: ServiceAccount
    name: provider-helm
    namespace: workspace
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io