apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: storage
spec:
  compositeTypeRef:
    apiVersion: epca.eo/v1beta1
    kind: XStorage
  mode: Pipeline
  pipeline:
  - step: bucket
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: bucket-results
        base:
          apiVersion: minio.crossplane.io/v1
          kind: Bucket
          metadata: {}
          spec:
            forProvider:
              region: eu-central-1
            providerConfigRef:
              name: provider-minio
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.namespace"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-results'
      - name: bucket-stage
        base:
          apiVersion: minio.crossplane.io/v1
          kind: Bucket
          metadata: {}
          spec:
            forProvider:
              region: eu-central-1
            providerConfigRef:
              name: provider-minio
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.namespace"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-stage'
      - name: policy-results
        base:
          apiVersion: minio.crossplane.io/v1
          kind: Policy
          metadata: {}
          spec:
            forProvider: {}
            providerConfigRef:
              name: provider-minio
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.namespace"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-results'
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.namespace"
          toFieldPath: "spec.forProvider.allowBucket"
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-results'
      - name: policy-stage
        base:
          apiVersion: minio.crossplane.io/v1
          kind: Policy
          metadata: {}
          spec:
            forProvider: {}
            providerConfigRef:
              name: provider-minio
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.namespace"
          toFieldPath: "metadata.name"
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-stage'
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.namespace"
          toFieldPath: "spec.forProvider.allowBucket"
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-stage'
      - name: user
        base:
          apiVersion: minio.crossplane.io/v1
          kind: User
          metadata: {}
          spec:
            forProvider:
              policies: []
            providerConfigRef:
              name: provider-minio
            writeConnectionSecretToRef:
              name: bucket
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.namespace"
          toFieldPath: "metadata.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.namespace"
          toFieldPath: "spec.writeConnectionSecretToRef.namespace"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.namespace"
          toFieldPath: "spec.forProvider.policies[0]"
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-results'
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.namespace"
          toFieldPath: "spec.forProvider.policies[1]"
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-stage'
        connectionDetails:
        - name: access
          type: FromConnectionSecretKey
          fromConnectionSecretKey: AWS_ACCESS_KEY_ID          
        - name: AWS_ACCESS_KEY_ID
          type: FromConnectionSecretKey
          fromConnectionSecretKey: AWS_ACCESS_KEY_ID          
        - name: secret
          type: FromConnectionSecretKey
          fromConnectionSecretKey: AWS_SECRET_ACCESS_KEY          
        - name: AWS_SECRET_ACCESS_KEY
          type: FromConnectionSecretKey
          fromConnectionSecretKey: AWS_SECRET_ACCESS_KEY          
        - name: bucketname
          type: FromFieldPath
          fromFieldPath: spec.claimRef.namespace