apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: alice
spec:
  providerConfigRef:
    name: provider-keycloak
  forProvider:
    username: alice
    realmId: eoepca
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: bob
spec:
  providerConfigRef:
    name: provider-keycloak
  forProvider:
    username: bob
    realmId: eoepca
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: eric
spec:
  providerConfigRef:
    name: provider-keycloak
  forProvider:
    username: eric
    realmId: eoepca
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: example-user-1
spec:
  providerConfigRef:
    name: provider-keycloak
  forProvider:
    username: example-user-1
    realmId: eoepca
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: example-user-2
spec:
  providerConfigRef:
    name: provider-keycloak
  forProvider:
    username: example-user-2
    realmId: eoepca
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: example-admin
  # annotations:
  #   crossplane.io/external-name: "11b75ef2-b964-48b1-8a43-6e3c8bdd4f33" 
spec:
  providerConfigRef:
    name: provider-keycloak
  forProvider:
    username: example-admin
    realmId: eoepca