apiVersion: epca.eo/v1beta1
kind: Workspace
metadata:
  name: ws-alice
  namespace: workspace
spec:
  subscription: gold
  owner: alice
---
apiVersion: epca.eo/v1beta1
kind: Workspace
metadata:
  name: ws-bob
  namespace: workspace
spec:
  subscription: gold
  owner: bob  
---
apiVersion: epca.eo/v1beta1
kind: Workspace
metadata:
  name: ws-eric
  namespace: workspace
spec:
  subscription: gold
  owner: eric
  extraBuckets:
    - ws-eric-shared
  grants:
    - bucket: ws-eric
      grantees:
      - ws-alice
    - bucket: ws-eric-shared
      grantees:
      - ws-alice
      - ws-bob
---
apiVersion: epca.eo/v1beta1
kind: Workspace
metadata:
  name: ws-example-team-1
  namespace: workspace
spec:
  subscription: gold
  owner: example-user-1
---
apiVersion: epca.eo/v1beta1
kind: Workspace
metadata:
  name: ws-example-team-2
  namespace: workspace
spec:
  subscription: bronze
  owner: example-user-1
  members:
    - example-user-2
  extraBuckets:
    - ws-example-team-2-stage
  grants:
    - bucket: ws-example-team-2-stage
      grantees:
      - ws-example-team-1