apiVersion: epca.eo/v1beta1
kind: Workspace
metadata:
  name: ws-example-team-1
  namespace: workspace
spec:
  subscription: gold
  owner: example-user-1
---
apiVersion: epca.eo/v1beta1
kind: Workspace
metadata:
  name: ws-example-team-2
  namespace: workspace
spec:
  subscription: bronze
  owner: example-user-1