apiVersion: epca.eo/v1beta1
kind: Workspace
metadata:
  name: ws-alice
  namespace: workspace
spec:
  subscription: gold
  owner: alice
  defaultBucket: ws-alice
  linkedBuckets:
    - ws-eric-shared # no access granted yet from ws-eric
---
apiVersion: epca.eo/v1beta1
kind: Workspace
metadata:
  name: ws-bob
  namespace: workspace
spec:
  subscription: gold
  owner: bob
  defaultBucket: ws-bob
  members:
    - example-user-1
  linkedBuckets:
    - ws-eric-shared # access granted from ws-eric 
---
apiVersion: epca.eo/v1beta1
kind: Workspace
metadata:
  name: ws-eric
  namespace: workspace
spec:
  subscription: gold
  owner: eric
  defaultBucket: ws-eric
  members:
    - example-user-1
    - example-user-2
  extraBuckets:
    - ws-eric-shared
  grants:
    - bucket: ws-eric-shared
      grantees:  
      - ws-bob