apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: alice
spec:
  providerConfigRef:
    name: provider-keycloak
  forProvider:
    username: alice
    realmId: eoepca
    email: alice@eoepca.org
    emailVerified: true
    firstName: Alice
    lastName: EOEPCA
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: bob
spec:
  providerConfigRef:
    name: provider-keycloak
  forProvider:
    username: bob
    realmId: eoepca
    email: bob@eoepca.org
    emailVerified: true
    firstName: Bob
    lastName: EOEPCA
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: eric
spec:
  providerConfigRef:
    name: provider-keycloak
  forProvider:
    username: eric
    realmId: eoepca
    email: eric@eoepca.org
    emailVerified: true
    firstName: Eric
    lastName: EOEPCA
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: example-user-1
spec:
  providerConfigRef:
    name: provider-keycloak
  forProvider:
    username: example-user-1
    realmId: eoepca
    email: example-user-1@eoepca.org
    emailVerified: true
    firstName: Example-user-1
    lastName: EOEPCA
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: example-user-2
spec:
  providerConfigRef:
    name: provider-keycloak
  forProvider:
    username: example-user-2
    realmId: eoepca
    email: example-user-2@eoepca.org
    emailVerified: true
    firstName: Example-user-2
    lastName: EOEPCA
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: example-admin
  # annotations:
  #   crossplane.io/external-name: "11b75ef2-b964-48b1-8a43-6e3c8bdd4f33" 
spec:
  providerConfigRef:
    name: provider-keycloak
  forProvider:
    username: example-admin
    realmId: eoepca
    email: example-admin@eoepca.org
    emailVerified: true
    firstName: Example-admin
    lastName: EOEPCA