openapi: 3.0.3
info:
  title: Workspace Storage Layer API
  description: API documentation for login, creating share links, and resolving share links.
  version: 1.0.0
servers:
  - url: https://<ws_name>.apx.develop.eoepca.org/api
paths:
  /login:
    get:
      summary: Login to obtain an authentication token
      description: Logs in a user and returns a login token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: default
                password:
                  type: string
                  example: changeme
              required:
                - username
                - password
      responses:
        '200':
          description: Successfully logged in.
          content:
            application/json:
              schema:
                type: string
                example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
  /share/sources/{path}:
    post:
      summary: Create a share link for a given path
      description: Requires authentication and generates a shareable link for a specified path.
      parameters:
        - name: path
          in: path
          required: true
          schema:
            type: string
          example: "application-package/s-expression/s-expression-0_0_2.cwl"
      responses:
        '200':
          description: Successfully created a share link.
          content:
            application/json:
              schema:
                type: object
                properties:
                  hash:
                    type: string
                    example: KjtmA0Bu
                  path:
                    type: string
                    example: "/sources/<ws_name>/application-package/s-expression/s-expression-0_0_2.cwl"
                  userID:
                    type: integer
                    example: 1
                  expire:
                    type: integer
                    example: 0
                  creationTime:
                    type: integer
                    example: 1736871971
      security:
        - bearerAuth: []
  /public/dl/{hash}:
    get:
      summary: Resolve a share link
      description: Resolves a share link and returns a presigned URL in the location header.
      parameters:
        - name: hash
          in: path
          required: true
          schema:
            type: string
          example: KjtmA0Bu
        - name: inline
          in: query
          required: false
          schema:
            type: boolean
            example: true
      responses:
        '200':
          description: Presigned URL redirection successful.
          headers:
            Location:
              description: Presigned URL for download.
              schema:
                type: string
          content:
            text/plain:
              schema:
                type: string
                example: "Presigned URL here"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
