apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: workspace
spec:
  compositeTypeRef:
    apiVersion: epca.eo/v1beta1
    kind: XWorkspace
  mode: Pipeline
  pipeline:
  - step: namespace
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: namespace
        base:
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata: {}
          spec:
            forProvider:
              manifest:
                apiVersion: v1
                kind: Namespace
                metadata:
                  labels:
                    workspace: "true"
            providerConfigRef:
              name: provider-kubernetes
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.manifest.metadata.name"
      - name: resourcequota
        base:
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata: {}
          spec:
            forProvider:
              manifest:
                apiVersion: v1
                kind: ResourceQuota
                metadata:
                  name: default
                spec:
                  hard: {}
            providerConfigRef:
              name: provider-kubernetes
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.manifest.metadata.namespace"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.subscription"
          toFieldPath: "spec.forProvider.manifest.spec.hard"
          transforms:
          - type: map
            map: 
              bronze:
                limits.cpu: 1500m
                limits.memory: 6Gi
                pods: "5"
                requests.cpu: "1"
                requests.memory: 4Gi
              silver:
                limits.cpu: "3"
                limits.memory: 12Gi
                pods: "10"
                requests.cpu: "2"
                requests.memory: 8Gi
              gold:
                limits.cpu: "6"
                limits.memory: 20Gi
                pods: "20"
                requests.cpu: "4"
                requests.memory: 16Gi
      - name: storage
        base:
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata: {}
          spec:
            forProvider:
              manifest:
                apiVersion: epca.eo/v1beta1
                kind: Storage
                metadata: 
                  name: default            
                spec:
                  location: EU
                  acl: private
                  writeConnectionSecretToRef:
                    name: bucket
            providerConfigRef:
              name: provider-kubernetes
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.manifest.metadata.namespace"
      - name: deployment-workspace-ui
        base:
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata: {}
          spec:
            forProvider:
              manifest:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: workspace-ui
                labels:
                  app.kubernetes.io/instance: workspace-ui
                  app.kubernetes.io/name: workspace-ui
                spec:
                  strategy:
                    rollingUpdate:
                      maxUnavailable: 0
                    type: RollingUpdate
                  replicas: 1
                  revisionHistoryLimit: 2
                  selector:
                    matchLabels:
                      app.kubernetes.io/instance: workspace-ui
                      app.kubernetes.io/name: workspace-ui
                  template:
                    metadata:
                      labels:
                        app.kubernetes.io/instance: workspace-ui
                        app.kubernetes.io/name: workspace-ui
                    spec:
                      containers:
                      - name: workspace-ui
                        image: ghcr.io/versioneer-tech/package-r:v1.2.5
                        ports:
                        - name: http
                          containerPort: 80
                          protocol: TCP
                        env:
                        - name: BUCKET_DEFAULT
                          value: "<replaced>"
                        - name: BRANDING_NAME
                          value: "Workspace UI"
                        - name: AWS_ACCESS_KEY_ID
                          valueFrom:
                            secretKeyRef:
                              name: bucket
                              key: access
                        - name: AWS_SECRET_ACCESS_KEY
                          valueFrom:
                            secretKeyRef:
                              name: bucket
                              key: secret
                        - name: AWS_REGION
                          value: eu-central-1
                        - name: AWS_ENDPOINT_URL
                          value: https://minio.develop.eoepca.org
                        - name: PASSWORD
                          value: "changeme"
                        resources:
                          limits:
                            cpu: 1
                            memory: 512Mi
                          requests:
                            cpu: 0.1
                            memory: 128Mi
                        imagePullPolicy: Always                  
            providerConfigRef:
              name: provider-kubernetes
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.manifest.metadata.namespace"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.manifest.spec.template.spec.containers[0].env[0].value"
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s-stage'
      - name: service-workspace-ui
        base:
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata: {}
          spec:
            forProvider:
              manifest:
                apiVersion: v1
                kind: Service
                metadata:
                  name: workspace-ui
                spec:
                  type: ClusterIP
                  selector:
                    app.kubernetes.io/instance: workspace-ui
                    app.kubernetes.io/name: workspace-ui
                  ports:
                    - name: http
                      protocol: TCP
                      port: 80
                      targetPort: http
            providerConfigRef:
              name: provider-kubernetes
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.manifest.metadata.namespace"
      - name: ingress-workspace-ui
        base:
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata: {}
          spec:
            forProvider:
              manifest:
                apiVersion: apisix.apache.org/v2
                kind: ApisixRoute
                metadata:
                  name: workspace-ui
                spec:
                  http:
                  - backends:
                    - serviceName: workspace-ui
                      servicePort: 8080
                    match:
                      hosts:
                      - <replaced>
                      paths:
                      - /share/*
                    name: public
                  - backends:
                    - serviceName: workspace-ui
                      servicePort: 8080
                    match:
                      hosts:
                      - <replaced>
                      paths:
                      - /*
                    name: protected
                    # plugins:
                    # - config:
                    #     access_token_in_authorization_header: true
                    #     client_id: ws-test4
                    #     client_secret: Qmp5p...
                    #     discovery: https://iam-auth.apx.develop.eoepca.org/realms/eoepca/.well-known/openid-configuration
                    #   enable: true
                    #   name: openid-connect
                    # - config:
                    #     client_id: ws-test4
                    #     client_secret: Qmp5p...
                    #     discovery: https://iam-auth.apx.develop.eoepca.org/realms/eoepca/.well-known/uma2-configuration
                    #     lazy_load_paths: true
                    #     ssl_verify: false
                    #   enable: true
                    #   name: authz-keycloak
                    websocket: true
            providerConfigRef:
              name: provider-kubernetes
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.manifest.metadata.namespace"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.manifest.spec.http[0].match.hosts[0]"
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s.apx.develop.eoepca.org'
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.manifest.spec.http[1].match.hosts[0]"
          transforms:
          - type: string
            string:
              type: Format
              fmt: '%s.apx.develop.eoepca.org'
      - name: source-workspace-ui
        base:
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata: {}
          spec:
            forProvider:
              manifest:
                apiVersion: package.r/alphav1
                kind: Source
                spec:
                  access:               
                    secretName: bucket
            providerConfigRef:
              name: provider-kubernetes
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.manifest.metadata.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.manifest.metadata.namespace"
      - name: source-global-workspace-ui
        base:
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata: {}
          spec:
            forProvider:
              manifest:
                apiVersion: package.r/alphav1
                kind: Source
                metadata:
                  namespace: workspace
            providerConfigRef:
              name: provider-kubernetes
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.manifest.metadata.name"
      - name: rolebinding-workspace-ui
        base:
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          metadata: {}
          spec:
            forProvider:
              manifest:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: RoleBinding                
                metadata:
                  name: default-view
                subjects:
                - kind: ServiceAccount
                  name: default
                  namespace: <replaced>
                roleRef:
                  kind: ClusterRole
                  name: view
                  apiGroup: rbac.authorization.k8s.io
            providerConfigRef:
              name: provider-kubernetes
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.manifest.metadata.namespace"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.manifest.subjects[0].namespace"
      - name: keycloak-group
        base:
          apiVersion: group.keycloak.crossplane.io/v1alpha1
          kind: Group
          spec:
            providerConfigRef:
              name: provider-keycloak
            forProvider:
              name: <replaced>
              realmId: eoepca
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "metadata.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.name"
      - name: keycloak-membership
        base:
          apiVersion: group.keycloak.crossplane.io/v1alpha1
          kind: Memberships
          spec:
            providerConfigRef:
              name: provider-keycloak
            forProvider:
              groupIdRef:
                name: <replaced>
                policy:
                  resolution: Required
              members:
              - <replaced>
              realmId: eoepca
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "metadata.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.groupIdRef.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.owner"
          toFieldPath: "spec.forProvider.members[0]"
      - name: keycloak-client
        base:
          apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
          kind: Client
          spec:
            providerConfigRef:
              name: provider-keycloak
            forProvider:
              accessType: CONFIDENTIAL
              standardFlowEnabled: true
              directAccessGrantsEnabled: true
              serviceAccountsEnabled: true
              authorization:
                - policyEnforcementMode: ENFORCING
              webOrigins: 
                - '/*'
              validRedirectUris:
                - '/*'
              realmId: eoepca
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "metadata.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.clientId"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.rootUrl"
          transforms:
          - type: string
            string:
              type: Format
              fmt: 'https://%s.apx.develop.eoepca.org'
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.adminUrl"
          transforms:
          - type: string
            string:
              type: Format
              fmt: 'https://%s.apx.develop.eoepca.org'
      - name: keycloak-role
        base:
          apiVersion: role.keycloak.crossplane.io/v1alpha1
          kind: Role
          spec:
            providerConfigRef:
              name: provider-keycloak
            forProvider:
              name: ws-access
              clientIdRef:
                policy:
                  resolution: Required
              realmId: eoepca
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "metadata.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.clientIdRef.name"
        - type: ToEnvironmentFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: roleId
      - name: keycloak-roles
        base:
          apiVersion: group.keycloak.crossplane.io/v1alpha1
          kind: Roles
          spec:
            providerConfigRef:
              name: provider-keycloak
            forProvider:
              realmId: "eoepca"
              groupIdRef:
                policy:
                  resolution: "Required"
              roleIdsRefs:
                - name: <replaced>
                  policy:
                    resolution: "Required"
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "metadata.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.groupIdRef.name"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.roleIdsRefs[0].name"
      - name: keycloak-clientrolepolicy
        base:
          apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
          kind: ClientRolePolicy
          spec:
            providerConfigRef:
              name: provider-keycloak
            forProvider:
              name: 'Role ws_access Policy'
              type: role
              decisionStrategy: UNANIMOUS
              logic: POSITIVE    
              realmId: eoepca
              role:
              - id: <replaced>
                required: false
              resourceServerIdRef:
                name: <replaced>
                policy:
                  resolution: Required
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "metadata.name"
        - type: FromEnvironmentFieldPath
          fromFieldPath: "roleId"
          toFieldPath: "spec.forProvider.role[0].id"
        - type: FromCompositeFieldPath
          fromFieldPath: "spec.claimRef.name"
          toFieldPath: "spec.forProvider.resourceServerIdRef.name"        