apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xworkspaces.epca.eo
spec:
  connectionSecretKeys: []
  group: epca.eo
  names:
    kind: XWorkspace
    plural: xworkspaces
  claimNames:
    kind: Workspace
    plural: workspaces
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                subscription:
                  type: string
                  default: silver
                owner:
                  type: string
              required:
                - owner