apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: example-user-1
spec:
  providerConfigRef:
    name: provider-keycloak
  forProvider:
    username: example-user-1
    realmId: eoepca
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: example-user-1
spec:
  providerConfigRef:
    name: provider-keycloak
  forProvider:
    username: example-user-1
    realmId: eoepca