apiVersion: v1
kind: Secret
metadata:
  name: cng-stac-api-registry
  labels:
    app: cng-stac-api
type: Opaque
stringData:
  host: {{REGISTRY_HOST}}
  username: {{REGISTRY_USERNAME}}
  password: {{REGISTRY_PASSWORD}}
  reference: {{OCI_REFERENCE}}
