apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: storage
spec:
  compositeTypeRef:
    apiVersion: epca.eo/v1beta1
    kind: XStorage
  mode: Pipeline
  pipeline:
    - step: setup-buckets-and-policies
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{- $xr := .observed.composite.resource }}
            {{- range $i, $bucket := $xr.spec.buckets }}
            ---
            apiVersion: minio.crossplane.io/v1
            kind: Bucket
            metadata:
              name: {{ $bucket.name }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: bucket-{{ $i }}
                gotemplating.fn.crossplane.io/ready: "True"
            spec:
              forProvider:
                region: ""
              providerConfigRef:
                name: provider-minio
            {{- range $j, $rw := $bucket.accessReadWrite }}
            ---
            apiVersion: minio.crossplane.io/v1
            kind: Policy
            metadata:
              name: {{ $bucket.name }}.readwrite.{{ $rw }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: policy-rw-{{ $i }}-{{ $j }}
                gotemplating.fn.crossplane.io/ready: "True"
            spec:
              forProvider:
                rawPolicy: |
                  {
                    "Version": "2012-10-17",
                    "Statement": [
                      {
                        "Effect": "Allow",
                        "Action": [
                          "s3:GetBucketLocation",
                          "s3:ListBucket",
                          "s3:GetObject",
                          "s3:PutObject",
                          "s3:DeleteObject"
                        ],
                        "Resource": [
                          "arn:aws:s3:::{{ $bucket.name }}",
                          "arn:aws:s3:::{{ $bucket.name }}/*"
                        ]
                      }
                    ]
                  }
              providerConfigRef:
                name: provider-minio
            {{- end }}
            {{- range $j, $ro := $bucket.accessReadOnly }}
            ---
            apiVersion: minio.crossplane.io/v1
            kind: Policy
            metadata:
              name: {{ $bucket.name }}.readonly.{{ $ro }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: policy-ro-{{ $i }}-{{ $j }}
                gotemplating.fn.crossplane.io/ready: "True"
            spec:
              forProvider:
                rawPolicy: |
                  {
                    "Version": "2012-10-17",
                    "Statement": [
                      {
                        "Effect": "Allow",
                        "Action": [
                          "s3:GetBucketLocation",
                          "s3:ListBucket"
                        ],
                        "Resource": [
                          "arn:aws:s3:::{{ $bucket.name }}"
                        ]
                      },
                      {
                        "Effect": "Allow",
                        "Action": [
                          "s3:GetObject"
                        ],
                        "Resource": [
                          "arn:aws:s3:::{{ $bucket.name }}/*"
                        ]
                      }
                    ]
                  }
              providerConfigRef:
                name: provider-minio
            {{- end }}
            {{- end }}
            {{- range $user := (uniq (concat (pluck "accessReadWrite" $xr.spec.buckets) (pluck "accessReadOnly" $xr.spec.buckets))) }}
            ---
            apiVersion: minio.crossplane.io/v1
            kind: User
            metadata:
              name: {{ $user }}
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: user-{{ $user }}
                gotemplating.fn.crossplane.io/ready: "True"
            spec:
              forProvider:
                userName: {{ $user }}
                policies:
                {{- range $i, $bucket := $xr.spec.buckets }}
                  {{- if has $user $bucket.accessReadWrite }}
                  - {{ $bucket.name }}.readwrite.{{ $user }}
                  {{- end }}
                  {{- if has $user $bucket.accessReadOnly }}
                  - {{ $bucket.name }}.readonly.{{ $user }}
                  {{- end }}
                {{- end }}
              providerConfigRef:
                name: provider-minio
              writeConnectionSecretToRef:
                name: bucket-{{ $user }}
                namespace: {{ $user }}
            {{- end }}
